# -*- coding: utf-8 -*-
"""global_mental_health_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AruUJpiu8RiKOpsAq6t_ce4l5_yfr5yM

#사회적 인식과 변화에 대한 추가적인 분석 (국가적 관점)

- 데이터 탐색 및 전처리
"""

import pandas as pd

file_path = "/content/1- mental-illnesses-prevalence.csv"

data = pd.read_csv(file_path)
data.head(10)

new_columns = [
    'Entity', 'Code', 'Year', 'Schizophrenia', 'Depressive disorders',
    'Anxiety disorders', 'Bipolar disorders', 'Eating disorders'
]
data.columns = new_columns  # 열 이름 변경

# 열 이름 변경 후 확인
print("Renamed Columns in dataset:")
print(data.columns)

"""##- 아시아 국가별 우울증 비교 분석"""

import plotly.express as px

# 국가별 우울증 비율 평균 계산
avg_depressive_disorders = data.groupby('Entity')['Depressive disorders'].mean().reset_index()

asia_countries = [
    'China', 'India', 'Japan', 'South Korea', 'Indonesia', 'Thailand',
    'Philippines', 'Vietnam', 'Malaysia', 'Singapore', 'Pakistan',
    'Bangladesh', 'Sri Lanka', 'Nepal', 'Bhutan', 'Maldives', 'Mongolia'
]

# 아시아 국가 데이터 필터링
asia_data = avg_depressive_disorders[avg_depressive_disorders['Entity'].isin(asia_countries)]

# 우울증 비율 기준으로 순위 계산
asia_data['Rank'] = asia_data['Depressive disorders'].rank(ascending=False)

# 결과 정렬 및 출력
asia_data = asia_data.sort_values(by='Depressive disorders', ascending=False)
print("Asian Countries by Depressive Disorders:")
print(asia_data)

# 시각화: 수평 막대 그래프 생성
fig = px.bar(
    asia_data,
    x='Depressive disorders',
    y='Entity',
    orientation='h',
    color='Depressive disorders',
    title="아시아 국가별 우울증 비교 분석",
    labels={"Entity": "Country", "Depressive disorders": "Depressive Disorders (Average %)"}
)

# 그래프 레이아웃 설정
fig.update_layout(
    xaxis_title="Depressive Disorders (Average %)",
    yaxis_title="Country",
    title_font_size=16
)

# 그래프 출력
fig.show()

"""##- 아시아 국가 연도별 우울증 비율 변화 분석"""

# 아시아 국가 데이터 필터링
asia_data = data[data['Entity'].isin(asia_countries)]

# 연도별 우울증 비율 변화 시각화
fig = px.line(
    asia_data,
    x='Year',
    y='Depressive disorders',
    color='Entity',
    title="연도별 우울증 비율 변화 시각화",
    labels={"Entity": "Country", "Depressive disorders": "Depressive Disorders (%)"}
)

# 그래프 레이아웃 설정
fig.update_layout(
    xaxis_title="Year",
    yaxis_title="Depressive Disorders (%)",
    title_font_size=16
)

# 그래프 출력
fig.show()

"""##- 대륙별 우울증 비교 분석"""

# 대륙별 국가 리스트 정의
continent_dict = {
    'Asia': [
        'China', 'India', 'Japan', 'South Korea', 'Indonesia', 'Thailand',
        'Philippines', 'Vietnam', 'Malaysia', 'Singapore', 'Pakistan',
        'Bangladesh', 'Sri Lanka', 'Nepal', 'Bhutan', 'Maldives', 'Mongolia'
    ],
    'Europe': [
        'Germany', 'France', 'United Kingdom', 'Italy', 'Spain', 'Poland',
        'Netherlands', 'Belgium', 'Sweden', 'Norway', 'Denmark', 'Finland'
    ],
    'Africa': [
        'Nigeria', 'South Africa', 'Ethiopia', 'Egypt', 'Kenya', 'Tanzania',
        'Uganda', 'Ghana', 'Mozambique', 'Zambia'
    ],
    'South America': [
        'Brazil', 'Argentina', 'Colombia', 'Chile', 'Peru', 'Venezuela',
        'Ecuador', 'Bolivia', 'Paraguay', 'Uruguay'
    ]
}

# 대륙별 필터링 및 평균 계산
continent_data = []
for continent, countries in continent_dict.items():
    filtered_data = data[data['Entity'].isin(countries)]
    avg_depressive = filtered_data['Depressive disorders'].mean()
    continent_data.append({'Continent': continent, 'Average Depressive Disorders': avg_depressive})

# 대륙별 데이터프레임 생성
continent_df = pd.DataFrame(continent_data)

# 시각화: 대륙별 평균 우울증 비율 비교
fig = px.bar(
    continent_df,
    x='Continent',
    y='Average Depressive Disorders',
    color='Continent',
    title="대륙별 평군 우울증 비율 비교",
    labels={"Continent": "Continent", "Average Depressive Disorders": "Depressive Disorders (%)"}
)

# 그래프 레이아웃 설정
fig.update_layout(
    xaxis_title="Continent",
    yaxis_title="Depressive Disorders (%)",
    title_font_size=16
)

# 그래프 출력
fig.show()

# 정신질환별 평균 비율 계산
disorder_columns = ['Schizophrenia', 'Depressive disorders',
                    'Anxiety disorders', 'Bipolar disorders', 'Eating disorders']
average_disorders = data[disorder_columns].mean().reset_index()
average_disorders.columns = ['Disorder', 'Average Percentage']

# 시각화: 정신질환별 평균 비율 비교
fig = px.bar(
    average_disorders,
    x='Disorder',
    y='Average Percentage',
    title="정신질환별 비율 비교",
    labels={"Disorder": "Mental Disorder", "Average Percentage": "Average Percentage (%)"},
    color='Disorder'
)

# 그래프 레이아웃 설정
fig.update_layout(
    xaxis_title="Mental Disorder",
    yaxis_title="Average Percentage (%)",
    title_font_size=16
)

# 그래프 출력
fig.show()